[package]
name = "predict"
version = "0.1.0"
authors = ["Ehsanul Hoque <ehsanul@ehsanul.com>"]

[dependencies]
fnv = "1.0"
nalgebra = "0.14"
ncollide = "0.14"
obj-rs = "0.4"
lazy_static = "1.0"
csv = "1"

[dependencies.state]
path = "../state"
