[package]
name = "generate-data"
version = "0.1.0"
authors = ["Ehsanul Hoque <ehsanul@ehsanul.com>"]

[dependencies]
nalgebra = "*"
bincode = "*"
flate2 = "1.0"
csv = "1.0"
rand = "0.6.5"
rayon = "1.1"

[dependencies.state]
path = "../state"

[dependencies.brain]
path = "../brain"
