[package]
name = "temp"
version = "0.1.0"
authors = ["Ehsanul Hoque <ehsanul@ehsanul.com>"]

[dependencies]
csv = "1"
gilrs = "0.6.0"

[dependencies.rlbot]
path = "../rlbot"

[dependencies.state]
path = "../state"