[package]
name = "brick-record"
version = "0.1.0"
authors = ["Ehsanul Hoque <ehsanul@ehsanul.com>"]

[dependencies]
csv = "1"
gilrs = "0.6.0"
rlbot = "0.0.6"
flatbuffers = "0.4.0"

[dependencies.state]
path = "../state"
