[package]
name = "heuristic"
version = "0.1.0"
authors = ["Ehsanul Hoque <ehsanul@ehsanul.com>"]

[dependencies]
tensorflow = "0.12.0"
kdtree = "0.5.1"
nalgebra = "*"
ord_subset = "3"
csv = "*"

[dependencies.state]
path = "../state"
